import type { NextComponentType } from "next";
import Head from "next/head";

export const HeadComponent: NextComponentType = () => {
    return (
        <Head>
            <title>Stephany Brito</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
};
